//
// Emulate "menuconfig"
//
#define CONFIG_BLUEPAD32_MAX_DEVICES 4
#define CONFIG_BLUEPAD32_MAX_ALLOWLIST 4
#define CONFIG_BLUEPAD32_GAP_SECURITY 2
#define CONFIG_BLUEPAD32_ENABLE_BLE_BY_DEFAULT 1
// #define CONFIG_BLUEPAD32_ENABLE_VIRTUAL_DEVICE_BY_DEFAULT 1

#define CONFIG_BLUEPAD32_PLATFORM_CUSTOM
#define CONFIG_TARGET_PICO_W

#if defined(_DEBUG) && (_DEBUG != 0)

#define CONFIG_BLUEPAD32_LOG_LEVEL 2  // 2 == Info

#else

#define CONFIG_BLUEPAD32_LOG_LEVEL 0  // 0 == None

#endif
